disp("问题3（1）y'=-20*(y-x^2)+2*x,0<=x<=1,N=5,10,20,y(0)=1/3");
a=0;b=1;
alpha=1/3;
syms x y;
f=@ (x,y) -20*(y-x^2)+2*x;
disp("n=5时：");
N=5;
[xn,yn]=Runge_Kutta(a,b,alpha,N,f);
fprintf('xn=%f,yn=%f\n',xn,yn);
disp("n=10时：");
N=10;
[xn,yn]=Runge_Kutta(a,b,alpha,N,f);
fprintf('xn=%f,yn=%f\n',xn,yn);
disp("n=20时：");
N=20;
[xn,yn]=Runge_Kutta(a,b,alpha,N,f);
fprintf('xn=%f,yn=%f\n',xn,yn);
disp("真实解：");
xn=1;yn=xn^2+1/3*exp(-20*xn);
fprintf('xn=%f,yn=%f\n',xn,yn);

disp("问题3（2）y'=-20*y+20*sin(x)+cos(x),0<=x<=1,N=5,10,20,y(0)=1");
a=0;b=1;
alpha=1;
syms x y;
f=@ (x,y) -20*y+20*sin(x)+cos(x);
disp("n=5时：");
N=5;
[xn,yn]=Runge_Kutta(a,b,alpha,N,f);
fprintf('xn=%f,yn=%f\n',xn,yn);
disp("n=10时：");
N=10;
[xn,yn]=Runge_Kutta(a,b,alpha,N,f);
fprintf('xn=%f,yn=%f\n',xn,yn);
disp("n=20时：");
N=20;
[xn,yn]=Runge_Kutta(a,b,alpha,N,f);
fprintf('xn=%f,yn=%f\n',xn,yn);
disp("真实解：");
xn=1;yn=exp(-20*xn)+sin(xn);
fprintf('xn=%f,yn=%f\n',xn,yn);

disp("问题3（3）y'=-20*(y-exp(x)*sin(x))+exp(x)*(sin(x)+cos(x)),0<=x<=1,N=5,10,20,y(0)=0");
a=0;b=1;
alpha=0;
syms x y;
f=@ (x,y) -20*(y-exp(x)*sin(x))+exp(x)*(sin(x)+cos(x));
disp("n=5时：");
N=5;
[xn,yn]=Runge_Kutta(a,b,alpha,N,f);
fprintf('xn=%f,yn=%f\n',xn,yn);
disp("n=10时：");
N=10;
[xn,yn]=Runge_Kutta(a,b,alpha,N,f);
fprintf('xn=%f,yn=%f\n',xn,yn);
disp("n=20时：");
N=20;
[xn,yn]=Runge_Kutta(a,b,alpha,N,f);
fprintf('xn=%f,yn=%f\n',xn,yn);
disp("真实解：");
xn=1;yn=exp(xn)*sin(xn);
fprintf('xn=%f,yn=%f\n',xn,yn);