disp("问题2（1）y'=2/x*y+x^2*exp(x),1<=x<=3,N=5,10,20,y(0)=0");
a=1;b=3;
alpha=0;
syms x y;
f=@ (x,y) 2/x*y+x^2*exp(x);
disp("n=5时：");
N=5;
[xn,yn]=Runge_Kutta(a,b,alpha,N,f);
fprintf('xn=%f,yn=%f\n',xn,yn);
disp("n=10时：");
N=10;
[xn,yn]=Runge_Kutta(a,b,alpha,N,f);
fprintf('xn=%f,yn=%f\n',xn,yn);
disp("n=20时：");
N=20;
[xn,yn]=Runge_Kutta(a,b,alpha,N,f);
fprintf('xn=%f,yn=%f\n',xn,yn);
disp("真实解：");
xn=3;yn=xn^2*(exp(xn)-exp(1));
fprintf('xn=%f,yn=%f\n',xn,yn);

disp("问题2（2）y'=1/x*(y^2+y),1<=x<=3,N=5,10,20,y(1)=-2");
a=1;b=3;
alpha=-2;
syms x y;
f=@ (x,y) 1/x*(y^2+y);
disp("n=5时：");
N=5;
[xn,yn]=Runge_Kutta(a,b,alpha,N,f);
fprintf('xn=%f,yn=%f\n',xn,yn);
disp("n=10时：");
N=10;
[xn,yn]=Runge_Kutta(a,b,alpha,N,f);
fprintf('xn=%f,yn=%f\n',xn,yn);
disp("n=20时：");
N=20;
[xn,yn]=Runge_Kutta(a,b,alpha,N,f);
fprintf('xn=%f,yn=%f\n',xn,yn);
disp("真实解：");
xn=3;yn=2*xn/(1-2*xn);
fprintf('xn=%f,yn=%f\n',xn,yn);
